/**
 * NOT auto-generated.
 *
 * This token provider exists to simplify the usage of auth tokens via the Trinsic SDK.
 *
 * The default (and only) token provider generated by the OpenAPI generator we use
 * employs a rate-limited approach, which doesn't work well at scale.
 */

using System.Linq;

namespace Trinsic.Api.Client
{
    /// <summary>
    /// Provides a token to the api clients.
    /// </summary>
    /// <typeparam name="TTokenBase"></typeparam>
    public class ConstantTokenProvider<TTokenBase> : TokenProvider<TTokenBase> where TTokenBase : TokenBase
    {
        internal TTokenBase _token;

        /// <summary>
        /// Instantiates a ConstantTokenProvider.
        /// </summary>
        public ConstantTokenProvider(TokenContainer<TTokenBase> tokenContainer) : base(tokenContainer.Tokens)
        {
            _token = tokenContainer.Tokens.First();
        }

        internal override async System.Threading.Tasks.ValueTask<TTokenBase> GetAsync(string header = "", System.Threading.CancellationToken cancellation = default)
        {
            return _token;
        }
    }
}
