name: Release API Java SDK (GIT)

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish Java Package
    uses: ./.github/workflows/api-java-action.yml
    concurrency:
      group: git-release
    with:
      publish: true
    secrets: inherit
