name: Release API Go SDK (GIT)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Publish Go Package
    uses: ./.github/workflows/api-go-action.yml
    concurrency:
      group: git-release
    with:
      publish: true
    secrets: inherit
