name: Build and Publish API Typescript SDK

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false
        description: "Publish the package, default is false"

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm ci
      - name: Generate backend SDK
        run: ./api-typescript/build-sdk.ps1
        shell: pwsh
      - name: Build sample
        run: ./api-typescript/build-samples.ps1
        shell: pwsh
      - name: Publish SDK
        if: inputs.publish == true
        run: ./api-typescript/publish-sdk.ps1
        shell: pwsh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
