name: Sync ReadMe docs with SDKs README.md files

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "api-csharp/README.md"
      - "api-go/README.md"
      - "api-java/README.md"
      - "api-php/README.md"
      - "api-python/README.md"
      - "api-ruby/README.md"
      - "api-typescript/README.md"
      - "ui-android/README.md"
      - "ui-expo/README.md"
      - "ui-flutter/README.md"
      - "ui-swift/README.md"
      - "ui-web/README.md"
      - ".readme/**"

jobs:
  api-csharp:
    name: Sync C# SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat api-csharp/README.md >> .readme/api-csharp.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/api-csharp.md --key=${{ secrets.README_API_KEY }} --version=0.1
  api-go:
    name: Sync Go SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat api-go/README.md >> .readme/api-go.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/api-go.md --key=${{ secrets.README_API_KEY }} --version=0.1
  api-java:
    name: Sync Java SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat api-java/README.md >> .readme/api-java.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/api-java.md --key=${{ secrets.README_API_KEY }} --version=0.1
  api-php:
    name: Sync PHP SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat api-php/README.md >> .readme/api-php.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/api-php.md --key=${{ secrets.README_API_KEY }} --version=0.1
  api-python:
    name: Sync Python SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat api-python/README.md >> .readme/api-python.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/api-python.md --key=${{ secrets.README_API_KEY }} --version=0.1
  api-ruby:
    name: Sync Ruby SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat api-ruby/README.md >> .readme/api-ruby.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/api-ruby.md --key=${{ secrets.README_API_KEY }} --version=0.1
  api-typescript:
    name: Sync TypeScript SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat api-typescript/README.md >> .readme/api-typescript.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/api-typescript.md --key=${{ secrets.README_API_KEY }} --version=0.1
  ui-android:
    name: Sync Android SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat ui-android/README.md >> .readme/ui-android.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/ui-android.md --key=${{ secrets.README_API_KEY }} --version=0.1
  ui-expo:
    name: Sync Expo SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat ui-expo/README.md >> .readme/ui-expo.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/ui-expo.md --key=${{ secrets.README_API_KEY }} --version=0.1
  ui-flutter:
    name: Sync Flutter SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat ui-flutter/README.md >> .readme/ui-flutter.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/ui-flutter.md --key=${{ secrets.README_API_KEY }} --version=0.1
  ui-swift:
    name: Sync Swift SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat ui-swift/README.md >> .readme/ui-swift.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/ui-swift.md --key=${{ secrets.README_API_KEY }} --version=0.1
  ui-web:
    name: Sync Web SDK Readme
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Prepare readme file
        run: cat ui-web/README.md >> .readme/ui-web.md
      - name: Run `docs` command
        uses: readmeio/rdme@v8
        with:
          rdme: docs .readme/ui-web.md --key=${{ secrets.README_API_KEY }} --version=0.1
