name: Build and Publish UI Android SDK

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false
        description: "Publish the package, default is false"

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build SDK
        run: ./ui-android/build-sdk.sh
        shell: bash
      - name: Build sample
        run: ./ui-android/build-samples.sh
        shell: bash
      - name: Publish SDK
        if: inputs.publish == true
        run: ./ui-android/publish-sdk.sh
        shell: bash
        env:
          MEWMBA_GIT_PUBLISH_TOKEN: ${{ secrets.MEWMBA_GIT_PUBLISH_TOKEN }}
          SDK_REPOSITORY_PATH: ${{ github.repository }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_PUBLISHING_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PUBLISHING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_PASSWORD }}
